sudo: false
services:
- docker
language: bash
script:
- docker build -t ansi/feelflight-1-0-weather:latest .
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker push ansi/feelflight-1-0-weather:latest
